### ISSUE TITLE
anisette-server error 

### ISSUE THREAD

**Issue by maxduke** [Dadoum/Provision#9] opened 2022-07-18 13:27 UTC
Hello,

I got the below error when I tried to run anisette-server
```
cannot find verneed/verdef for version index=2 referenced by symbol "fstat" at "/opt/build/anisette-server/lib/x86_64/libCoreADI.so"
ERR: cannot load library lib/x86_64/libCoreADI.so
cannot find verneed/verdef for version index=2 referenced by symbol "pthread_create" at "/opt/build/anisette-server/lib/x86_64/libstoreservicescore.so"
ERR: cannot load library lib/x86_64/libstoreservicescore.so
ERR: cannot load symbol kq56gsgHG6:
ERR: cannot load symbol Sph98paBcz:
ERR: cannot load symbol nf92ngaK92:
ERR: cannot load symbol p435tmhbla:
ERR: cannot load symbol tn46gtiuhw:
ERR: cannot load symbol fy34trz2st:
ERR: cannot load symbol uv5t6nhkui:
ERR: cannot load symbol rsegvyrt87:
ERR: cannot load symbol aslgmuibau:
ERR: cannot load symbol jk24uiwqrg:
ERR: cannot load symbol qi864985u0:
ERR: cannot load symbol ksbafgljkb:
ERR: cannot load symbol madsvsfvjk:
WARN: Generation of unique identifier failed, using a generic one instead.
Segmentation fault
```

**Comment by Dadoum** [comment] 2022-07-18 16:03
What is your Linux distribution ?

**Comment by Dadoum** [comment] 2022-07-19 08:48
Try with the last commit, does it work now ?

**Comment by Dadoum** [comment] 2022-07-19 11:11
(it's now built if you want to grab the latest version without compiling it yourself)

**Comment by Dadoum** [comment] 2022-07-19 14:39
Can you build it yourself ? It's related to the Glibc version in the GitHub action which is too recent for your distribution. I will probable downgrade it soon for better compatibility.

**Comment by Dadoum** [comment] 2022-07-19 15:42
Can you try the latest build ? (of anisette_server).

I can't reproduce the issue in a VM, so I tried a dirty fix.

**Comment by Dadoum** [comment] 2022-07-20 11:46
There is now a lot more logging with the latest artefact (retrieve-headers-debug). And I tried another fix.

**Comment by Dadoum** [comment] 2022-07-20 21:08
The output still stops at `WARN: Generation of unique identifier failed, using a generic one instead.` ? (with retrieve-headers-debug)

**Comment by lilili87222** [comment] 2022-07-21 03:50
delete ./adi and try .   I test the last version . it works now.

**Comment by Dadoum** [comment] 2022-07-21 09:59
in /home/$USER/.adi, but I don't think it's due to that.

**Comment by Dadoum** [comment] 2022-07-26 19:25
I have trouble reproducing your issue in a VM. Can you try to debug it with GDB?

Here is the procedure:

- Install GDB
Then launch commands as in this terminal:
```bash
[dadoum@fedora retrieve-headers-debug]$ gdb ./retrieve_headers
GNU gdb (GDB) Fedora 12.1-3.fc37
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./retrieve_headers...
(gdb) r
... some output ...
(gdb) bt
[COPY WHAT APPEARS HERE]
```
And send the backtrace here. If you have debuginfod, it would be even better but I don't think it's included in Debian.

**Comment by Dadoum** [comment] 2022-07-27 10:47
The last build of retrieve-headers-debug should have more logging. Can you send me the output with this one too ?

**Comment by Dadoum** [comment] 2022-07-28 10:59
Go at line 30 and add in the target_link_libraries "rt" and "pthread".
```
target_link_libraries(provision PUBLIC PkgConfig::plist hybris stdc++ rt pthread)
```
Does it work better ?

**Comment by Dadoum** [comment] 2022-07-29 00:49
Edit: I actually updated the repo, you can try the last build if you prefer.

**Comment by Dadoum** [comment] 2022-07-29 19:03
OK, you need to compile it on your device since old Glibc versions (Glibc 2.24) does not ship with lstat in the shared library. They are indeed statically linked automatically with the linker script in `libc6-dev`. So if you miss this package, install it (even if I think you already have it installed).

**Comment by Dadoum** [comment] 2022-07-30 21:25
Your issue should be fixed now. Can you retry ?

**Comment by Dadoum** [comment] 2022-08-01 01:12
Feel free to re-open issue if you are still encountering problems

**Closed by Dadoum** 2022-08-01 01:12 UTC

**Comment by Dadoum** [comment] 2022-08-01 10:14
Yes, it tries to use libsystemd to generate a unique identifier but a lot of systems don't have this library, and since it's not important as long as you don't share your adi file with someone else, I didn't make a fallback method.
